### ISSUE TITLE
.x ld script problems

### ISSUE THREAD

**Issue by segobi** [idc/ps4-fake-405#1]
Hi, when i keep the DISCARD instruction im getting this error when compiling/linking:
discarded output section: `.got.plt'

when I remove that instruction the .bin and its byte array seem to become too large for the payload_installer to include it.

**Comment by idc** [comment]
What compiler? But yes, we don't want GOT section or anything.

**Comment by segobi** [comment]
gcc version 6.3.0 20170516 (Debian 6.3.0-18)

**Comment by segobi** [comment]
working on centos 7.. thanks.

**Comment by segobi** [comment]
with gcc 4.8
